// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vendaLanchesAsp.Context;

namespace vendaLanchesAsp.Migrations
{
//    [DbContext(typeof(AppDbContext))]
//    [Migration("20210201140409_Categoria")]
//    partial class Categoria
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .UseIdentityColumns()
//                .HasAnnotation("Relational:MaxIdentifierLength", 128)
//                .HasAnnotation("ProductVersion", "5.0.2");

//            modelBuilder.Entity("vendaLanchesAsp.Models.CarrinhoCompraItem", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .UseIdentityColumn();

//                    b.Property<string>("CarrinhoCompraId")
//                        .HasMaxLength(200)
//                        .HasColumnType("nvarchar(200)");

//                    b.Property<int?>("LancheId")
//                        .HasColumnType("int");

//                    b.Property<int>("Quantidade")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("LancheId");

//                    b.ToTable("CarrinhoCompraItem");
//                });

//            modelBuilder.Entity("vendaLanchesAsp.Models.Categoria", b =>
//                {
//                    b.Property<int>("CategoriaId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .UseIdentityColumn();

//                    b.Property<string>("CategoriaNome")
//                        .HasMaxLength(200)
//                        .HasColumnType("nvarchar(200)");

//                    b.Property<string>("Descricao")
//                        .HasMaxLength(200)
//                        .HasColumnType("nvarchar(200)");

//                    b.HasKey("CategoriaId");

//                    b.ToTable("Categorias");
//                });

//            modelBuilder.Entity("vendaLanchesAsp.Models.Lanche", b =>
//                {
//                    b.Property<int>("LancheId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .UseIdentityColumn();

//                    b.Property<int>("CategoriaId")
//                        .HasColumnType("int");

//                    b.Property<string>("DescricaoCurta")
//                        .HasMaxLength(200)
//                        .HasColumnType("nvarchar(200)");

//                    b.Property<string>("DescricaoDetalhada")
//                        .HasMaxLength(200)
//                        .HasColumnType("nvarchar(200)");

//                    b.Property<bool>("EmEstoque")
//                        .HasColumnType("bit");

//                    b.Property<string>("ImagemThumbnailUrl")
//                        .HasMaxLength(250)
//                        .HasColumnType("nvarchar(250)");

//                    b.Property<string>("ImagemUrl")
//                        .HasMaxLength(250)
//                        .HasColumnType("nvarchar(250)");

//                    b.Property<bool>("IsLanchePreferido")
//                        .HasColumnType("bit");

//                    b.Property<string>("Nome")
//                        .HasMaxLength(200)
//                        .HasColumnType("nvarchar(200)");

//                    b.Property<decimal>("Preco")
//                        .HasColumnType("decimal(18,2)");

//                    b.HasKey("LancheId");

//                    b.HasIndex("CategoriaId");

//                    b.ToTable("Lanches");
//                });

//            modelBuilder.Entity("vendaLanchesAsp.Models.CarrinhoCompraItem", b =>
//                {
//                    b.HasOne("vendaLanchesAsp.Models.Lanche", "Lanche")
//                        .WithMany()
//                        .HasForeignKey("LancheId");

//                    b.Navigation("Lanche");
//                });

//            modelBuilder.Entity("vendaLanchesAsp.Models.Lanche", b =>
//                {
//                    b.HasOne("vendaLanchesAsp.Models.Categoria", "Categoria")
//                        .WithMany("Lanches")
//                        .HasForeignKey("CategoriaId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Categoria");
//                });

//            modelBuilder.Entity("vendaLanchesAsp.Models.Categoria", b =>
//                {
//                    b.Navigation("Lanches");
//                });
//#pragma warning restore 612, 618
//        }
//    }
}
